version: '2'
services:
  kanboard:
    image: kanboard/kanboard:v1.2.22
    ports:
      - "8081:80"
    volumes:
      - ./kanboard_data:/var/www/app/data
      - ./kanboard_plugins:/var/www/app/plugins
      - ./kanboard_ssl:/etc/nginx/ssl
    restart: always